# Generated by Django 4.2.14 on 2024-08-02 04:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import world.models.line


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0000_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=2)),
                ('system', models.CharField(max_length=50)),
                ('operative_status', models.CharField(max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('updated_at', models.DateTimeField()),
                ('flyer', models.ImageField(upload_to=world.models.line.Line.user_directory_path)),
            ],
        ),
    ]
