# Generated by Django 4.2.14 on 2024-08-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='name',
            new_name='route',
        ),
        migrations.AddField(
            model_name='line',
            name='mode',
            field=models.CharField(choices=[('published', 'Publicado'), ('draft', 'En borrador')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='line',
            name='operative_status',
            field=models.CharField(choices=[('open', 'En Operación'), ('closed', 'Fuera de Servicio'), ('construction', 'En construcción')], max_length=15),
        ),
        migrations.AlterField(
            model_name='line',
            name='system',
            field=models.CharField(choices=[('stc', 'STC Metro'), ('metrobus', 'Metrobus'), ('cablebus', 'Cablebus'), ('tren-ligero', 'Tren Ligero'), ('tren-suburbano', 'Tren Suburbano'), ('rtp', 'Red de Transporte de Pasajeros (RTP)'), ('ecobici', 'Ecobici'), ('transporte-concesionado', 'Transporte Concesionado'), ('tren-interurbano', 'Tren Interurbano'), ('mexibus', 'Mexibus'), ('mexicable', 'Mexicable')], max_length=50),
        ),
    ]
