# Generated by Django 4.2.14 on 2024-08-11 17:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_rename_name_line_route_line_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(dim=3, srid=4326),
        ),
    ]
