# Generated by Django 4.2.15 on 2024-08-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_alter_line_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
