# Generated by Django 3.2.25 on 2024-09-27 18:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_locationcategory_remove_poi_category_poi_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('system', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=10)),
                ('station_number', models.CharField(max_length=10)),
                ('station_key', models.CharField(max_length=10)),
                ('station_eod_key', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('municipalities_served', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_identifier', models.BigIntegerField()),
                ('system_identifier', models.CharField(max_length=10)),
                ('line', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField()),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.station')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('system_identifier', 'card_identifier', 'datetime'), name='unique_card_datetime'),
        ),
    ]
