# Generated by Django 3.2.25 on 2024-09-27 18:52

from django.db import migrations, models
import world.models.line


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_auto_20240927_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='flyer',
            field=models.ImageField(null=True, upload_to=world.models.line.Line.user_directory_path),
        ),
    ]
