# Generated by Django 4.2.16 on 2024-11-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_alter_line_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
