# Generated by Django 4.2.16 on 2024-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_line_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='line',
        ),
        migrations.AddField(
            model_name='station',
            name='lines',
            field=models.ManyToManyField(related_name='stations', to='world.line'),
        ),
    ]
