# Generated by Django 4.2.16 on 2024-11-29 19:35

from django.db import migrations, models
import world.models.station


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_remove_station_line_station_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='icon',
            field=models.ImageField(null=True, upload_to=world.models.station.Station.user_directory_path),
        ),
    ]
