# Generated by Django 4.2.16 on 2024-11-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_station_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
