# Generated by Django 4.2.17 on 2024-12-08 07:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_alter_station_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geozone_key', models.CharField(max_length=15)),
                ('population', models.FloatField()),
                ('population_employed', models.FloatField()),
                ('population_unemployed', models.FloatField()),
                ('population_density', models.IntegerField()),
                ('houses', models.FloatField()),
                ('population_disabled', models.FloatField()),
                ('population_with_car', models.FloatField()),
                ('houses_empty', models.FloatField()),
                ('socioeconomic_category', models.CharField(blank=True, max_length=50, null=True)),
                ('poverty_category', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
