# Generated by Django 4.2.17 on 2024-12-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_geozone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozone',
            name='poverty_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
