# Generated by Django 4.2.17 on 2024-12-08 07:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0017_alter_geozone_poverty_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(dim=3, null=True, srid=4326),
        ),
    ]
