# Generated by Django 4.2.17 on 2024-12-09 01:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0019_alter_line_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
