# Generated by Django 4.2.17 on 2024-12-12 16:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0020_alter_line_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.CharField(max_length=10)),
                ('vehicle_id', models.CharField(max_length=10)),
                ('time_minutes_left', models.IntegerField()),
                ('vehicle_line', models.CharField(max_length=100)),
                ('vehicle_destination', models.CharField(max_length=100)),
                ('vehicle_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
