# Generated by Django 4.2.17 on 2024-12-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0021_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='VehicleLocation',
        ),
    ]
