# Generated by Django 4.2.17 on 2024-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0022_rename_location_vehiclelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='json_response',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
