# Generated by Django 4.2.17 on 2024-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0023_vehiclelocation_json_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocation',
            name='json_response',
            field=models.TextField(),
        ),
    ]
