# Generated by Django 4.2.17 on 2024-12-13 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0024_alter_vehiclelocation_json_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
