# Generated by Django 4.2.17 on 2024-12-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0025_vehiclelocation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_number',
            field=models.IntegerField(),
        ),
    ]
