# Generated by Django 4.2.17 on 2024-12-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0026_alter_station_station_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_eod_key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_key',
            field=models.CharField(max_length=20),
        ),
    ]
