# Generated by Django 4.2.17 on 2024-12-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0027_alter_station_station_eod_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='identifier',
            field=models.CharField(max_length=4),
        ),
    ]
