# Generated by Django 4.2.17 on 2024-12-18 21:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_alter_line_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenueRecord',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('clee', models.CharField()),
                ('nom_estab', models.CharField()),
                ('raz_social', models.CharField(blank=True, null=True)),
                ('codigo_act', models.CharField()),
                ('nombre_act', models.CharField()),
                ('per_ocu', models.CharField()),
                ('tipo_vial', models.CharField()),
                ('nom_vial', models.CharField()),
                ('tipo_v_e_1', models.CharField()),
                ('nom_v_e_1', models.CharField()),
                ('tipo_v_e_2', models.CharField()),
                ('nom_v_e_2', models.CharField()),
                ('tipo_v_e_3', models.CharField()),
                ('nom_v_e_3', models.CharField()),
                ('numero_ext', models.CharField()),
                ('letra_ext', models.CharField(blank=True, null=True)),
                ('edificio', models.CharField(blank=True, null=True)),
                ('edificio_e', models.CharField(blank=True, null=True)),
                ('numero_int', models.CharField(blank=True, null=True)),
                ('letra_int', models.CharField(blank=True, null=True)),
                ('tipo_asent', models.CharField()),
                ('nomb_asent', models.CharField()),
                ('tipoCenCom', models.CharField(blank=True, null=True)),
                ('nom_CenCom', models.CharField(blank=True, null=True)),
                ('num_local', models.CharField(blank=True, null=True)),
                ('cod_postal', models.CharField()),
                ('cve_ent', models.CharField()),
                ('entidad', models.CharField()),
                ('cve_mun', models.CharField()),
                ('municipio', models.CharField()),
                ('cve_loc', models.CharField()),
                ('localidad', models.CharField()),
                ('ageb', models.CharField()),
                ('manzana', models.CharField()),
                ('telefono', models.CharField(blank=True, null=True)),
                ('correoelec', models.EmailField(blank=True, max_length=254, null=True)),
                ('www', models.URLField(blank=True, null=True)),
                ('tipoUniEco', models.CharField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_alta', models.DateField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
