# Generated by Django 4.2.17 on 2024-12-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0029_denuerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuerecord',
            name='numero_ext',
            field=models.CharField(blank=True, null=True),
        ),
    ]
