# Generated by Django 4.2.17 on 2024-12-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0030_alter_denuerecord_numero_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuerecord',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='longitud',
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='tipoUniEco',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='tipo_asent',
            field=models.CharField(blank=True, null=True),
        ),
    ]
