# Generated by Django 4.2.17 on 2024-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0031_remove_denuerecord_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuerecord',
            name='cod_postal',
            field=models.CharField(blank=True, null=True),
        ),
    ]
