# Generated by Django 4.2.17 on 2024-12-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0032_alter_denuerecord_cod_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuerecord',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='nom_v_e_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='nom_v_e_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='nom_v_e_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='nom_vial',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='nomb_asent',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='tipo_v_e_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='tipo_v_e_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='tipo_v_e_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuerecord',
            name='tipo_vial',
            field=models.CharField(blank=True, null=True),
        ),
    ]
