# Generated by Django 4.2.17 on 2024-12-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0033_alter_denuerecord_fecha_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuerecord',
            name='correoelec',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='nom_v_e_1',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='nom_v_e_2',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='nom_v_e_3',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='nom_vial',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='tipo_v_e_1',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='tipo_v_e_2',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='tipo_v_e_3',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='tipo_vial',
        ),
        migrations.RemoveField(
            model_name='denuerecord',
            name='www',
        ),
    ]
