# Generated by Django 4.2.17 on 2024-12-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0034_remove_denuerecord_correoelec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='companies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='education',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='jobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='leisure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='provision',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
