# Generated by Django 4.2.17 on 2024-12-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0035_geozone_companies_geozone_education_geozone_health_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geozone',
            name='geozone_key',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='houses',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='houses_empty',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='population_density',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='population_disabled',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='population_employed',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='population_unemployed',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='population_with_car',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='poverty_category',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='socioeconomic_category',
        ),
        migrations.AddField(
            model_name='geozone',
            name='CVEGEO',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='CVE_AGEB',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='CVE_ENT',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='CVE_LOC',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='CVE_MUN',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='bikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='geozone',
            name='cars',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='geozone',
            name='motorcycles',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='population',
            field=models.IntegerField(),
        ),
    ]
