# Generated by Django 4.2.17 on 2024-12-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0036_remove_geozone_geozone_key_remove_geozone_houses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozone',
            name='population',
            field=models.IntegerField(blank=True),
        ),
    ]
