# Generated by Django 4.2.17 on 2024-12-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0037_alter_geozone_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozone',
            name='population',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
