# Generated by Django 4.2.17 on 2024-12-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0038_alter_geozone_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozone',
            name='CVE_LOC',
            field=models.CharField(blank=True, null=True),
        ),
    ]
