# Generated by Django 4.2.17 on 2024-12-24 05:54

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0039_alter_geozone_cve_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='companies_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(srid=4326), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='education_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(srid=4326), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='health_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(srid=4326), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='jobs_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(srid=4326), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='leisure_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(srid=4326), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='provision_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(srid=4326), blank=True, default=list, size=None),
        ),
    ]
