# Generated by Django 4.2.17 on 2024-12-24 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0040_geozone_companies_list_geozone_education_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozone',
            name='companies_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='education_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='health_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='jobs_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='leisure_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='provision_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
