# Generated by Django 4.2.17 on 2024-12-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0041_alter_geozone_companies_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozone',
            name='bikes',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='cars',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='companies',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='education',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='health',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='jobs',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='leisure',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='motorcycles',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='provision',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
