# Generated by Django 4.2.17 on 2024-12-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0042_alter_geozone_bikes_alter_geozone_cars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozone',
            name='motorcycles',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
