# Generated by Django 4.2.17 on 2024-12-25 07:28

from django.db import migrations, models
import world.models.station


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0043_alter_geozone_motorcycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozone',
            name='bikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='cars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='companies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='education',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='jobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='leisure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='motorcycles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geozone',
            name='provision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='operative_status',
            field=models.CharField(choices=[('open', 'En Operación'), ('closed', 'Fuera de Servicio'), ('construction', 'En construcción'), ('proposal', 'Propuesta')], max_length=15),
        ),
        migrations.AlterField(
            model_name='station',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=world.models.station.Station.user_directory_path),
        ),
    ]
