# Generated by Django 4.2.17 on 2024-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0044_alter_geozone_bikes_alter_geozone_cars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='theme',
            field=models.CharField(default='sta', max_length=5),
        ),
    ]
