# Generated by Django 4.2.17 on 2024-12-28 20:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0045_line_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
