# Generated by Django 4.2.17 on 2024-12-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0046_line_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
