# Generated by Django 4.2.17 on 2024-12-29 18:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('world', '0047_alter_line_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='line',
            name='system',
            field=models.CharField(choices=[('stc', 'STC Metro'), ('metrobus', 'Metrobus'), ('cablebus', 'Cablebus'), ('tren-ligero', 'Tren Ligero'), ('tren-suburbano', 'Tren Suburbano'), ('rtp', 'RTP'), ('ecobici', 'Ecobici'), ('transporte-concesionado', 'Transporte Concesionado'), ('tren-interurbano', 'Tren Interurbano'), ('mexibus', 'Mexibus'), ('mexicable', 'Mexicable')], max_length=50),
        ),
    ]
