# Generated by Django 4.2.17 on 2024-12-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0048_line_tags_alter_line_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_300', models.IntegerField(default=0)),
                ('population_500', models.IntegerField(default=0)),
                ('population_1000', models.IntegerField(default=0)),
                ('population_2000', models.IntegerField(default=0)),
                ('health_300', models.IntegerField(default=0)),
                ('health_500', models.IntegerField(default=0)),
                ('health_1000', models.IntegerField(default=0)),
                ('health_2000', models.IntegerField(default=0)),
                ('education_300', models.IntegerField(default=0)),
                ('education_500', models.IntegerField(default=0)),
                ('education_1000', models.IntegerField(default=0)),
                ('education_2000', models.IntegerField(default=0)),
                ('leisure_300', models.IntegerField(default=0)),
                ('leisure_500', models.IntegerField(default=0)),
                ('leisure_1000', models.IntegerField(default=0)),
                ('leisure_2000', models.IntegerField(default=0)),
                ('jobs_300', models.IntegerField(default=0)),
                ('jobs_500', models.IntegerField(default=0)),
                ('jobs_1000', models.IntegerField(default=0)),
                ('jobs_2000', models.IntegerField(default=0)),
                ('companies_300', models.IntegerField(default=0)),
                ('companies_500', models.IntegerField(default=0)),
                ('companies_1000', models.IntegerField(default=0)),
                ('companies_2000', models.IntegerField(default=0)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='world.station')),
            ],
        ),
    ]
