# Generated by Django 4.2.17 on 2024-12-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0049_stationstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationstats',
            name='companies_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='companies_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='companies_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='companies_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='education_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='education_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='education_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='education_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='health_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='health_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='health_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='health_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='jobs_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='jobs_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='jobs_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='jobs_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='leisure_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='leisure_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='leisure_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='leisure_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='population_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='population_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='population_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationstats',
            name='population_500',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
