# Generated by Django 4.2.17 on 2025-01-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0050_alter_stationstats_companies_1000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationstats',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='world.station'),
        ),
    ]
