# Generated by Django 4.2.17 on 2025-01-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0053_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
    ]
