# Generated by Django 4.2.17 on 2025-01-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0055_alter_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='file',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='user_details/'),
        ),
    ]
