# Generated by Django 4.2.17 on 2025-01-11 05:00

from django.db import migrations, models
import django.db.models.deletion
import world.models.marker_icon


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0056_remove_userdetails_file_userdetails_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=world.models.marker_icon.MarkerIcon.image_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='line',
            name='system',
            field=models.CharField(choices=[('stc', 'STC Metro'), ('metrobus', 'Metrobus'), ('cablebus', 'Cablebus'), ('tren-ligero', 'Tren Ligero'), ('tren-suburbano', 'Tren Suburbano'), ('rtp', 'RTP'), ('ecobici', 'Ecobici'), ('transporte-concesionado', 'Transporte Concesionado'), ('tren-interurbano', 'Tren Interurbano'), ('mexibus', 'Mexibus'), ('mexicable', 'Mexicable'), ('paseo-ciclista', 'Paseo Ciclista')], max_length=50),
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.markericon')),
            ],
        ),
    ]
