# Generated by Django 4.2.17 on 2025-01-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0057_markericon_alter_line_system_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='markericon',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
