# Generated by Django 4.2.17 on 2025-01-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0058_markericon_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='world.line'),
            preserve_default=False,
        ),
    ]
