# Generated by Django 4.2.17 on 2025-01-11 07:07

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0059_marker_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
