# Generated by Django 4.2.17 on 2025-01-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0060_marker_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='world.line'),
        ),
    ]
