# Generated by Django 4.2.17 on 2025-01-12 22:20

from django.db import migrations, models
import django.db.models.deletion
import world.models.user_funny_pic


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0061_alter_marker_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFunnyPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=world.models.user_funny_pic.UserFunnyPic.user_pic_path)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='default_picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.userfunnypic'),
        ),
    ]
