# Generated by Django 4.2.17 on 2025-01-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0062_userfunnypic_userdetails_default_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfunnypic',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
