# Generated by Django 4.2.17 on 2025-01-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0063_userfunnypic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
