# Generated by Django 4.2.17 on 2025-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0064_station_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='slug',
            field=models.SlugField(default='1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
