# Generated by Django 4.2.17 on 2025-01-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0065_line_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='default_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.userfunnypic'),
        ),
    ]
