# Generated by Django 4.2.17 on 2025-01-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0066_alter_userdetails_default_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='is_a_valid_measurement',
            field=models.BooleanField(default=True),
        ),
    ]
