# Generated by Django 4.2.17 on 2025-01-22 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0067_vehiclelocation_is_a_valid_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclelocation',
            old_name='is_a_valid_measurement',
            new_name='is_fake_location',
        ),
    ]
