# Generated by Django 4.2.17 on 2025-01-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0068_rename_is_a_valid_measurement_vehiclelocation_is_fake_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocation',
            name='is_fake_location',
            field=models.BooleanField(default=False),
        ),
    ]
