# Generated by Django 4.2.17 on 2025-01-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0069_alter_vehiclelocation_is_fake_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='is_fake_location',
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='is_intrapolated',
            field=models.BooleanField(default=False),
        ),
    ]
