# Generated by Django 4.2.17 on 2025-01-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0070_remove_vehiclelocation_is_fake_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='has_been_processed',
            field=models.BooleanField(default=False),
        ),
    ]
