# Generated by Django 4.2.17 on 2025-01-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0071_vehiclelocation_has_been_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='is_outside_line',
            field=models.BooleanField(default=False),
        ),
    ]
