# Generated by Django 4.2.17 on 2025-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0072_vehiclelocation_is_outside_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocation',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
