# Generated by Django 4.2.17 on 2025-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0073_alter_vehiclelocation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='interpolated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclelocation',
            unique_together={('interpolated_date', 'is_intrapolated', 'vehicle_id', 'vehicle_location')},
        ),
    ]
