# Generated by Django 4.2.19 on 2025-02-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0074_vehiclelocation_interpolated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geozone',
            old_name='bikes',
            new_name='bikes_rate',
        ),
        migrations.RenameField(
            model_name='geozone',
            old_name='cars',
            new_name='cars_rate',
        ),
        migrations.RenameField(
            model_name='geozone',
            old_name='motorcycles',
            new_name='housing',
        ),
        migrations.AddField(
            model_name='geozone',
            name='motorcycles_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='bikes_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='bikes_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='bikes_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='bikes_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='cars_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='cars_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='cars_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='cars_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='housing_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='housing_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='housing_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='housing_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='motorcycles_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='motorcycles_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='motorcycles_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationstats',
            name='motorcycles_500',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
