# Generated by Django 4.2.19 on 2025-03-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0075_rename_bikes_geozone_bikes_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Feminine'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='system',
            field=models.CharField(choices=[('stc', 'STC Metro'), ('metrobus', 'Metrobus'), ('cablebus', 'Cablebus'), ('tren-ligero', 'Tren Ligero'), ('tren-suburbano', 'Tren Suburbano'), ('rtp', 'RTP'), ('ecobici', 'Ecobici'), ('transporte-concesionado', 'Transporte Concesionado'), ('tren-interurbano', 'Tren Interurbano'), ('mexibus', 'Mexibus'), ('mexicable', 'Mexicable'), ('va-y-ven', 'Va y Ven'), ('paseo-ciclista', 'Paseo Ciclista')], max_length=50),
        ),
    ]
