# Generated by Django 4.2.19 on 2025-03-20 09:30

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0076_userdetails_date_of_birth_userdetails_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness_value', models.IntegerField(help_text='Value from 1 to 5')),
                ('report_type', models.CharField(choices=[('all_good', '✅ Todo bien'), ('delayed', '⏰ Transporte retrasado'), ('crowded', '👥 Transporte lleno'), ('stolen', '🚫 Me robaron'), ('harassed', '😖 Me acosaron'), ('broken', '🔧 Fallas en el transporte'), ('other', 'Otro')], max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_address', models.TextField()),
                ('event_location_category', models.CharField(choices=[('not_applicable', 'No aplica'), ('cablebus', 'Cablebús'), ('concesionados', 'Transporte Concesionado'), ('ecobici', 'Ecobici'), ('electricos', 'Trolebús'), ('insurgente', 'Tren el Insurgente'), ('mexibus', 'Mexibús'), ('mexicable', 'Mexicable'), ('metro', 'Metro'), ('metrobus', 'Metrobús'), ('peseros', 'Peseros'), ('rtp', 'RTP'), ('suburbano', 'Tren Suburbano'), ('tren_ligero', 'Tren Ligero'), ('other', 'Otro')], max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='status_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
