# Generated by Django 4.2.19 on 2025-03-20 23:07

from django.db import migrations, models
import django.db.models.deletion
import world.models.avatar


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0077_userstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=world.models.avatar.Avatar.avatar_path)),
                ('identifier', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='default_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.avatar'),
        ),
    ]
