# Generated by Django 4.2.19 on 2025-03-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0078_avatar_userdetails_default_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
