# Generated by Django 4.2.19 on 2025-03-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0079_avatar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
