# Generated by Django 4.2.19 on 2025-03-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0080_userstatus_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
