# Generated by Django 4.2.19 on 2025-04-06 19:17

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0081_alter_userstatus_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bike_theft', 'Asaltos frecuentes'), ('bike_friendly', 'Lugar bici-amigable'), ('bike_danger', 'Peligro (Accidente)'), ('bike_shop', 'Tienda de bicis'), ('bike_workshop', 'Taller de bicis'), ('bike_parking', 'Bici-estacionamiento')], max_length=50)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='bike_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
