# Generated by Django 4.2.19 on 2025-04-08 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0083_alter_avatar_id_alter_bikereport_id_alter_geozone_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeReportFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='world.bikereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_bike_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bike_report_favorites',
                'unique_together': {('user', 'bike_report')},
            },
        ),
    ]
