# Generated by Django 4.2.19 on 2025-04-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0084_bikereportfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('content_type', models.CharField(max_length=50)),
                ('flag_reason', models.CharField(choices=[('bullying', 'Bullying'), ('fraud', 'Fraud'), ('spam', 'Spam'), ('adult_content', 'Adult Content'), ('hate_violence', 'Hate/Violence'), ('dont_want_to_see', "Don't Want to See"), ('other', 'Other')], max_length=50)),
                ('additional_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_flags',
                'indexes': [models.Index(fields=['content_id', 'content_type'], name='content_fla_content_7650b5_idx')],
            },
        ),
    ]
