# Generated by Django 4.2.20 on 2025-04-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0085_contentflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
