# Generated by Django 4.2.20 on 2025-04-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0087_linemetadata_stationmetadata_metrobusline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablebusline',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Visual and status metadata for this line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cablebus_line', to='world.linemetadata'),
        ),
        migrations.AlterField(
            model_name='cablebusstation',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Status metadata for this station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cablebus_station', to='world.stationmetadata'),
        ),
        migrations.AlterField(
            model_name='concesionadosline',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Visual and status metadata for this line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concesionados_line', to='world.linemetadata'),
        ),
        migrations.AlterField(
            model_name='concesionadosstation',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Status metadata for this station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concesionados_station', to='world.stationmetadata'),
        ),
        migrations.AlterField(
            model_name='interurbanoline',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Visual and status metadata for this line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interurbano_line', to='world.linemetadata'),
        ),
        migrations.AlterField(
            model_name='interurbanostation',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Status metadata for this station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interurbano_station', to='world.stationmetadata'),
        ),
        migrations.AlterField(
            model_name='metrobusline',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Visual and status metadata for this line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrobus_line', to='world.linemetadata'),
        ),
        migrations.AlterField(
            model_name='metrobusstation',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Status metadata for this station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrobus_station', to='world.stationmetadata'),
        ),
        migrations.AlterField(
            model_name='metroline',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Visual and status metadata for this line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metro_line', to='world.linemetadata'),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Status metadata for this station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metro_station', to='world.stationmetadata'),
        ),
        migrations.AlterField(
            model_name='rtpline',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Visual and status metadata for this line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtp_line', to='world.linemetadata'),
        ),
        migrations.AlterField(
            model_name='rtpstation',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Status metadata for this station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtp_station', to='world.stationmetadata'),
        ),
        migrations.AlterField(
            model_name='suburbanoline',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Visual and status metadata for this line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suburbano_line', to='world.linemetadata'),
        ),
        migrations.AlterField(
            model_name='suburbanostation',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Status metadata for this station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suburbano_station', to='world.stationmetadata'),
        ),
        migrations.AlterField(
            model_name='trenligeroline',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Visual and status metadata for this line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tren_ligero_line', to='world.linemetadata'),
        ),
        migrations.AlterField(
            model_name='trenligerostation',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Status metadata for this station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tren_ligero_station', to='world.stationmetadata'),
        ),
        migrations.AlterField(
            model_name='trolebusline',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Visual and status metadata for this line', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trolebus_line', to='world.linemetadata'),
        ),
        migrations.AlterField(
            model_name='trolebusstation',
            name='metadata',
            field=models.OneToOneField(blank=True, help_text='Status metadata for this station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trolebus_station', to='world.stationmetadata'),
        ),
    ]
