# Generated by Django 4.2.20 on 2025-04-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0088_alter_cablebusline_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linemetadata',
            old_name='thickness',
            new_name='stroke',
        ),
    ]
