# Generated by Django 4.2.20 on 2025-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0089_rename_thickness_linemetadata_stroke'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rtpline',
            name='world_rtpli_route_104dcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='rtpline',
            name='world_rtpli_status_8039ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='rtpline',
            name='world_rtpli_system_3693e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='rtpstation',
            name='world_rtpst_route_fcf7b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='rtpstation',
            name='world_rtpst_interse_426edd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='concesionadosline',
            unique_together={('system', 'nomenclature', 'route', 'origin_destination')},
        ),
        migrations.AlterUniqueTogether(
            name='rtpstation',
            unique_together={('route', 'direction', 'origin_destination', 'corridor', 'intersection')},
        ),
        migrations.AddIndex(
            model_name='rtpline',
            index=models.Index(fields=['route', 'system', 'origin', 'destination'], name='world_rtpli_route_8d00bd_idx'),
        ),
    ]
