# Generated by Django 4.2.20 on 2025-04-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0090_remove_rtpline_world_rtpli_route_104dcf_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rtpstation',
            unique_together=set(),
        ),
    ]
