# Generated by Django 4.2.20 on 2025-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0091_alter_rtpstation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolebusstation',
            name='boroughs',
            field=models.CharField(blank=True, help_text='Boroughs where the station is located', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trolebusstation',
            name='has_ramp',
            field=models.BooleanField(default=False, help_text='Whether the station has a ramp'),
        ),
    ]
