# Generated by Django 4.2.20 on 2025-04-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0092_alter_trolebusstation_boroughs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemetadata',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Whether the line is listed but should not be visible on the map'),
        ),
    ]
