# Generated by Django 4.2.20 on 2025-04-24 11:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0093_linemetadata_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='MexicableStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('system', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=10)),
                ('station_number', models.CharField(max_length=10)),
                ('station_code', models.CharField(max_length=10, unique=True)),
                ('station_type', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.stationmetadata')),
            ],
        ),
    ]
