# Generated by Django 4.2.20 on 2025-04-24 12:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0094_mexicablestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mexicablestation',
            name='station_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='MexicableLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=50)),
                ('line_number', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.linemetadata')),
            ],
        ),
    ]
