# Generated by Django 4.2.20 on 2025-04-24 16:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0095_alter_mexicablestation_station_number_mexicableline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MexibusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('system', models.CharField(default='mexibus', max_length=50, verbose_name='System')),
                ('line_number', models.CharField(max_length=50, verbose_name='Line Number')),
                ('station_number', models.IntegerField(verbose_name='Station Number')),
                ('station_code', models.CharField(max_length=50, verbose_name='Station Code')),
                ('station_type', models.CharField(blank=True, choices=[('Terminal', 'Terminal'), ('Terminal / Transbordo', 'Terminal / Transfer'), ('Intermedia', 'Intermediate')], max_length=50, null=True, verbose_name='Station Type')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mexibus_station', to='world.stationmetadata')),
            ],
            options={
                'verbose_name': 'Mexibus Station',
                'verbose_name_plural': 'Mexibus Stations',
                'ordering': ['line_number', 'station_number'],
            },
        ),
    ]
