# Generated by Django 4.2.20 on 2025-04-24 17:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0096_mexibusstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MexibusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(default='Mexibus', max_length=50, verbose_name='System')),
                ('line_number', models.CharField(max_length=10, verbose_name='Line Number')),
                ('route', models.CharField(max_length=255, verbose_name='Route')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('length', models.FloatField(verbose_name='Length (km)')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Geometry')),
                ('metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mexibus_line', to='world.linemetadata')),
            ],
            options={
                'verbose_name': 'Mexibus Line',
                'verbose_name_plural': 'Mexibus Lines',
                'ordering': ['line_number'],
            },
        ),
    ]
