# Generated by Django 4.2.20 on 2025-04-24 18:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0097_mexibusline'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcobiciStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(default='Ecobici', max_length=50, verbose_name='System')),
                ('station_id', models.CharField(max_length=10, verbose_name='Station ID')),
                ('main_street', models.CharField(max_length=255, verbose_name='Main Street')),
                ('secondary_street', models.CharField(max_length=255, verbose_name='Secondary Street')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Neighborhood')),
                ('borough', models.CharField(max_length=100, verbose_name='Borough')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('installation_type', models.CharField(max_length=50, verbose_name='Installation Type')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecobici_station', to='world.stationmetadata')),
            ],
            options={
                'verbose_name': 'Ecobici Station',
                'verbose_name_plural': 'Ecobici Stations',
                'ordering': ['station_id'],
            },
        ),
    ]
