# Generated by Django 4.2.20 on 2025-04-27 20:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0098_ecobicistation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness_value', models.IntegerField(help_text='User happiness rating for the station', verbose_name='Happiness Value')),
                ('report_type', models.CharField(help_text='Type of report (e.g., stolen, maintenance, etc.)', max_length=50, verbose_name='Report Type')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates of the review', srid=4326, verbose_name='Location')),
                ('message', models.TextField(help_text='User message or description', verbose_name='Message')),
                ('image', models.ImageField(blank=True, help_text='Optional image attached to the review', null=True, upload_to='station_reviews/', verbose_name='Image')),
                ('transport_id', models.IntegerField(help_text='ID of the transport system', verbose_name='Transport ID')),
                ('transport_identifier', models.CharField(help_text='Identifier of the transport (e.g., STC0219)', max_length=50, verbose_name='Transport Identifier')),
                ('transport_system', models.CharField(help_text='Name of the transport system (e.g., metro)', max_length=50, verbose_name='Transport System')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the review was created', verbose_name='Created At')),
                ('user_details', models.ForeignKey(help_text='User details associated with the review', on_delete=django.db.models.deletion.CASCADE, to='world.userdetails', verbose_name='User Details')),
            ],
            options={
                'verbose_name': 'Station Review',
                'verbose_name_plural': 'Station Reviews',
                'indexes': [models.Index(fields=['transport_id'], name='world_stati_transpo_761dc5_idx'), models.Index(fields=['transport_system'], name='world_stati_transpo_80a921_idx'), models.Index(fields=['created_at'], name='world_stati_created_5890eb_idx'), models.Index(fields=['user_details'], name='world_stati_user_de_d2c37b_idx')],
            },
        ),
    ]
