# Generated by Django 4.2.20 on 2025-04-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0099_stationreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_table_id', models.IntegerField(help_text='ID of the content being voted on', verbose_name='Reference Table ID')),
                ('reference_table_type', models.CharField(default='StationReview', help_text='Type of content being voted on (e.g., StationReview)', max_length=50, verbose_name='Reference Table Type')),
                ('is_positive', models.BooleanField(help_text='Whether the vote is positive (upvote) or negative (downvote)', verbose_name='Is Positive')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the vote was cast', verbose_name='Created At')),
                ('user_details', models.ForeignKey(help_text='User who cast the vote', on_delete=django.db.models.deletion.CASCADE, to='world.userdetails', verbose_name='User Details')),
            ],
            options={
                'indexes': [models.Index(fields=['reference_table_id', 'reference_table_type'], name='world_votin_referen_6179c3_idx'), models.Index(fields=['user_details'], name='world_votin_user_de_22d27b_idx')],
                'unique_together': {('reference_table_id', 'reference_table_type', 'user_details')},
            },
        ),
    ]
