# Generated by Django 4.2.20 on 2025-04-28 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0100_voting'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stationreview',
            name='world_stati_user_de_d2c37b_idx',
        ),
        migrations.RemoveIndex(
            model_name='voting',
            name='world_votin_user_de_22d27b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stationreview',
            name='user_details',
        ),
        migrations.AddField(
            model_name='stationreview',
            name='user',
            field=models.ForeignKey(default=1, help_text='User associated with the review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voting',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who cast the vote', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together={('reference_table_id', 'reference_table_type', 'user')},
        ),
        migrations.AddIndex(
            model_name='stationreview',
            index=models.Index(fields=['user'], name='world_stati_user_id_851a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='voting',
            index=models.Index(fields=['user'], name='world_votin_user_id_755ef0_idx'),
        ),
        migrations.RemoveField(
            model_name='voting',
            name='user_details',
        ),
    ]
