# Generated by Django 4.2.20 on 2025-04-28 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0101_remove_stationreview_world_stati_user_de_d2c37b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stationreview',
            name='world_stati_created_5890eb_idx',
        ),
        migrations.AddField(
            model_name='stationreview',
            name='review_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date of the review (day only)', verbose_name='Review Date'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='stationreview',
            index=models.Index(fields=['review_date'], name='world_stati_review__324592_idx'),
        ),
    ]
