# Generated by Django 4.2.20 on 2025-04-28 14:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0102_remove_stationreview_world_stati_created_5890eb_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationreview',
            unique_together={('transport_id', 'transport_identifier', 'review_date', 'user')},
        ),
    ]
