# Generated by Django 4.2.20 on 2025-04-30 19:31

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0103_alter_stationreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationreview',
            name='reviewed_object_location',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), help_text='Geographic coordinates of the reviewed object', srid=4326, verbose_name='Reviewed Object Location'),
            preserve_default=False,
        ),
    ]
