# Generated by Django 4.2.20 on 2025-05-03 22:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0104_stationreview_reviewed_object_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Felony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('start_month', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('crime_year', models.FloatField()),
                ('crime_month', models.CharField(max_length=20)),
                ('crime_date', models.DateField()),
                ('crime_time', models.TimeField()),
                ('crime_date_time', models.DateTimeField()),
                ('crime_type', models.CharField(max_length=255)),
                ('crime_category', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(blank=True, max_length=255, null=True)),
                ('prosecutor_office', models.CharField(max_length=255)),
                ('agency', models.CharField(max_length=50)),
                ('investigation_unit', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=255)),
                ('neighborhood_catalog', models.CharField(max_length=255)),
                ('borough', models.CharField(max_length=255)),
                ('borough_catalog', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Felony',
                'verbose_name_plural': 'Felonies',
                'indexes': [models.Index(fields=['crime_date'], name='world_felon_crime_d_bbaedb_idx'), models.Index(fields=['crime_type'], name='world_felon_crime_t_4cfc95_idx'), models.Index(fields=['borough'], name='world_felon_borough_085528_idx')],
            },
        ),
    ]
