# Generated by Django 4.2.20 on 2025-05-13 19:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0105_felony'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgebRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=6365)),
                ('geo_key', models.CharField(db_column='cvegeo', help_text='Geographic key of the AGEB', max_length=13, unique=True)),
                ('municipality_key', models.CharField(db_column='cve_mum', help_text='Municipality key', max_length=5)),
                ('borough', models.CharField(db_column='alcaldia', help_text='Name of the borough', max_length=100)),
                ('entity', models.CharField(db_column='entidad', help_text='Name of the entity', max_length=100)),
                ('sexual_abuse_risk_level', models.CharField(blank=True, help_text='Risk level', max_length=100, null=True)),
                ('metrobus_agression_risk_level', models.CharField(blank=True, help_text='Risk level', max_length=100, null=True)),
                ('taxi_theft_risk_level', models.CharField(blank=True, help_text='Risk level', max_length=100, null=True)),
                ('robbery_risk_level', models.CharField(blank=True, help_text='Risk level', max_length=100, null=True)),
                ('harassment_risk_level', models.CharField(blank=True, help_text='Risk level', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'AGEB Risk',
                'verbose_name_plural': 'AGEB Risks',
                'indexes': [models.Index(fields=['geo_key'], name='world_agebr_cvegeo_e62a48_idx'), models.Index(fields=['municipality_key'], name='world_agebr_cve_mum_07519e_idx'), models.Index(fields=['borough'], name='world_agebr_alcaldi_3a2db4_idx')],
            },
        ),
    ]
