# Generated by Django 4.2.20 on 2025-05-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0106_agebrisk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agebrisk',
            name='robbery_risk_level',
        ),
        migrations.AddField(
            model_name='agebrisk',
            name='microbus_theft_risk_level',
            field=models.CharField(blank=True, help_text='Microbus theft risk level', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agebrisk',
            name='taxi_theft_risk_level',
            field=models.CharField(blank=True, help_text='Taxi theft risk level', max_length=100, null=True),
        ),
    ]
