# Generated by Django 4.2.20 on 2025-07-13 04:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0110_geozone_house_thefts_2017_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='concesionados_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='concesionados_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='metro_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='metro_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='metrobus_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='metrobus_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='mexibus_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='mexibus_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='mexicable_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='mexicable_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='rtp_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='rtp_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='tren_interurbano_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='tren_interurbano_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='tren_ligero_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='tren_ligero_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='tren_suburbano_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='tren_suburbano_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
