# Generated by Django 4.2.20 on 2025-07-13 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0111_geozone_concesionados_stations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='cablebus_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='cablebus_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='ecobici_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='ecobici_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
