# Generated by Django 4.2.20 on 2025-07-14 00:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0112_geozone_cablebus_stations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbListing',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('host_id', models.BigIntegerField()),
                ('host_name', models.CharField(blank=True, max_length=255, null=True)),
                ('neighbourhood_group', models.CharField(blank=True, max_length=100, null=True)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('room_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_nights', models.IntegerField(blank=True, null=True)),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('last_review', models.DateField(blank=True, null=True)),
                ('reviews_per_month', models.FloatField(blank=True, null=True)),
                ('calculated_host_listings_count', models.IntegerField(default=1)),
                ('availability_365', models.IntegerField(blank=True, null=True)),
                ('number_of_reviews_ltm', models.IntegerField(default=0)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Airbnb Listing',
                'verbose_name_plural': 'Airbnb Listings',
                'db_table': 'world_airbnb_listing',
                'indexes': [models.Index(fields=['neighbourhood'], name='world_airbn_neighbo_f7aa0c_idx'), models.Index(fields=['room_type'], name='world_airbn_room_ty_bdf144_idx'), models.Index(fields=['host_id'], name='world_airbn_host_id_b39598_idx')],
            },
        ),
    ]
