# Generated by Django 4.2.20 on 2025-07-14 01:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0113_airbnblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_price_average_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_price_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
