# Generated by Django 4.2.20 on 2025-07-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0114_geozone_airbnb_listings_geozone_airbnb_listings_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geozone',
            name='airbnb_listings_price_average_list',
        ),
        migrations.RemoveField(
            model_name='geozone',
            name='airbnb_listings_price_list',
        ),
    ]
