# Generated by Django 4.2.20 on 2025-07-17 07:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0115_remove_geozone_airbnb_listings_price_average_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_code', models.CharField(help_text='Municipality code', max_length=10)),
                ('municipality_name', models.CharField(help_text='Municipality name', max_length=200)),
                ('neighbourhood_code', models.CharField(help_text='Neighbourhood code', max_length=20)),
                ('neighbourhood_name', models.CharField(help_text='Neighbourhood name', max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Geographic boundary of the neighbourhood', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Neighbourhood',
                'verbose_name_plural': 'Neighbourhoods',
                'indexes': [models.Index(fields=['municipality_code'], name='world_neigh_municip_3a9665_idx'), models.Index(fields=['municipality_name'], name='world_neigh_municip_04f52a_idx'), models.Index(fields=['neighbourhood_code'], name='world_neigh_neighbo_942a45_idx'), models.Index(fields=['neighbourhood_name'], name='world_neigh_neighbo_7b3395_idx')],
            },
        ),
    ]
