# Generated by Django 4.2.20 on 2025-07-17 07:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0116_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cablebus_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cablebus_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2017_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2018_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2019_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2020_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2021_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2022',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2022_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2023',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2023_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2024',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='cell_phone_thefts_2024_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='companies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='companies_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='concesionados_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='concesionados_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='ecobici_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='ecobici_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='education',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='education_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2017_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2018_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2019_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2020_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2021_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2022',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2022_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2023',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2023_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2024',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='harrasment_2024_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2017_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2018_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2019_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2020_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2021_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2022',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2022_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2023',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2023_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2024',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='house_thefts_2024_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='housing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='jobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='jobs_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='leisure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='leisure_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='metro_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='metro_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='metrobus_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='metrobus_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='mexibus_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='mexibus_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='mexicable_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='mexicable_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='population',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='provision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='provision_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='rtp_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='rtp_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2017_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2018_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2019_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2020_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2021_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2022',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2022_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2023',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2023_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2024',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='sexual_assault_2024_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2017_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2018_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2019_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2020_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2021_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2022',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2022_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2023',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2023_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2024',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='taxi_thefts_2024_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2017_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2018_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2019_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2020_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2021_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2022',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2022_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2023',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2023_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2024',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='thefts_2024_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tren_interurbano_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tren_interurbano_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tren_ligero_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tren_ligero_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tren_suburbano_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tren_suburbano_stations_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
