# Generated by Django 4.2.20 on 2025-07-17 16:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0118_remove_geozone_cell_phone_thefts_2017_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2017_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2018_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2019_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2020_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2021_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2022',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2022_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2023',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2023_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2024',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='business_thefts_2024_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2017',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2017_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2018',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2018_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2019_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2020',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2020_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2021',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2021_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2022',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2022_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2023',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2023_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2024',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business_thefts_2024_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
    ]
