# Generated by Django 4.2.20 on 2025-07-17 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0119_geozone_business_thefts_2017_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_entire_hotel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_entire_hotel_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_entire_hotel_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_entire_hotel_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_full_house',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_full_house_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_full_house_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_full_house_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_private_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_private_room_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_private_room_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_private_room_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_shared_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_shared_room_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_shared_room_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='airbnb_listings_shared_room_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_entire_hotel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_entire_hotel_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_entire_hotel_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_entire_hotel_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_full_house',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_full_house_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_full_house_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_full_house_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_private_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_private_room_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_private_room_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_private_room_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_shared_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_shared_room_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_shared_room_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='airbnb_listings_shared_room_price_average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
