# Generated by Django 4.2.20 on 2025-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0120_geozone_airbnb_listings_entire_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='housing_no_automotor',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='housing_with_automotor',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='housing_with_bicycle',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='housing_with_internet',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='housing_with_motorcycle',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='housing_with_pay_tv',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_education_level',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_education_level_men',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_education_level_women',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_men',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_men_older_than_60',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_ratio_men_women',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_with_disability',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_with_healthcare',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_with_no_healthcare',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_women',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='population_women_older_than_60',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
