# Generated by Django 4.2.20 on 2025-08-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0121_geozone_housing_no_automotor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='housing_without_internet',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='geozone',
            name='housing_without_pay_tv',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
