# Generated by Django 5.2.5 on 2025-08-20 00:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0122_geozone_housing_without_internet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device advertising identifier', max_length=255)),
                ('id_type', models.CharField(choices=[('IDFA', 'IDFA (iOS)'), ('ADID', 'ADID (Android)')], help_text='Ad ID device type: IDFA (iOS) or ADID (Android)', max_length=10)),
                ('latitude', models.FloatField(help_text='Latitude of the event')),
                ('longitude', models.FloatField(help_text='Longitude of the event')),
                ('horizontal_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic point for the location', null=True, srid=4326)),
                ('timestamp', models.BigIntegerField(help_text='Unix timestamp of the event (millisecond)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our system')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the event', null=True)),
                ('device_os', models.CharField(choices=[('iOS', 'iOS'), ('android', 'Android')], help_text='Device operating system: iOS or android', max_length=10)),
                ('os_version', models.CharField(blank=True, help_text='Device operating system version', max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Web browser version and operating system', null=True)),
                ('country', models.CharField(blank=True, help_text='ISO2 2-digit alpha country code of the event', max_length=2, null=True)),
                ('geohash', models.CharField(blank=True, help_text='Unique location alphanumeric string', max_length=20, null=True)),
                ('source_id', models.CharField(blank=True, help_text='Quadrant unique identifier for data source', max_length=255, null=True)),
                ('publisher_id', models.CharField(blank=True, help_text='Unique developer identifier', max_length=255, null=True)),
                ('app_id', models.CharField(blank=True, help_text='Unique application identifier', max_length=255, null=True)),
                ('location_context', models.CharField(blank=True, choices=[('0', 'Foreground'), ('1', 'Background')], help_text='0 = foreground | 1 = background', max_length=1, null=True)),
                ('consent', models.CharField(blank=True, choices=[('0', 'NA'), ('1', 'Yes')], help_text='0 = NA | 1 = yes', max_length=1, null=True)),
                ('quad_id', models.CharField(blank=True, help_text="Quadrant's unique device identifier", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Phone Location',
                'verbose_name_plural': 'Phone Locations',
                'db_table': 'phone_location',
                'indexes': [models.Index(fields=['device_id'], name='phone_locat_device__2a0795_idx'), models.Index(fields=['timestamp'], name='phone_locat_timesta_30d89e_idx'), models.Index(fields=['created_at'], name='phone_locat_created_64cde3_idx'), models.Index(fields=['device_os'], name='phone_locat_device__5f0bd9_idx'), models.Index(fields=['country'], name='phone_locat_country_512a9e_idx'), models.Index(fields=['app_id'], name='phone_locat_app_id_6fcf14_idx'), models.Index(fields=['quad_id'], name='phone_locat_quad_id_a7eec8_idx')],
            },
        ),
    ]
