# Generated by Django 4.2.25 on 2025-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0123_phonelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonelocation',
            name='is_within_cdmx',
            field=models.BooleanField(default=False, help_text='Whether the location is within the CDMX'),
        ),
    ]
