# Generated by Django 4.2.26 on 2025-11-14 19:05

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0124_phonelocation_is_within_cdmx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caid', models.CharField(db_index=True, help_text='Cryptographic advertising ID (hashed device identifier)', max_length=64)),
                ('utc_timestamp', models.DateTimeField(db_index=True, help_text='UTC timestamp of the trip event')),
                ('latitude', models.FloatField(help_text='Latitude of the trip location')),
                ('longitude', models.FloatField(help_text='Longitude of the trip location')),
                ('horizontal_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic point for the location', null=True, srid=4326)),
                ('id_type', models.CharField(choices=[('idfa', 'IDFA (iOS)'), ('aaid', 'AAID (Android)')], help_text='Ad ID device type: IDFA (iOS) or AAID (Android)', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the event', null=True)),
                ('iso_country_code', models.CharField(db_index=True, help_text='ISO 2-letter country code', max_length=2)),
                ('poi_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='Array of Point of Interest IDs', null=True, size=None)),
                ('traverse_time', models.IntegerField(blank=True, help_text='Trip traverse time in seconds', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading direction in degrees', null=True)),
                ('heading_cardinal', models.CharField(blank=True, help_text='Cardinal direction (North, South, East, West, etc.)', max_length=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='Trip start time', null=True)),
                ('pings', models.IntegerField(blank=True, help_text='Number of pings in the trip', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Trip end time', null=True)),
                ('overlap_flag', models.BooleanField(blank=True, help_text='Whether the trip overlaps with another trip', null=True)),
                ('high_velocity_flag', models.BooleanField(blank=True, help_text='Whether the trip has high velocity', null=True)),
                ('high_velocity_pings', models.IntegerField(blank=True, help_text='Number of high velocity pings', null=True)),
                ('overlap_trip_list', models.TextField(blank=True, help_text='List of overlapping trip IDs', null=True)),
                ('velocity', models.FloatField(blank=True, help_text='Trip velocity', null=True)),
                ('displacement', models.FloatField(blank=True, help_text='Trip displacement distance', null=True)),
                ('trip_index', models.IntegerField(blank=True, help_text='Trip index number', null=True)),
                ('trip_fields', models.JSONField(blank=True, help_text='Original trip_fields array data', null=True)),
                ('trip_ping_fields', models.JSONField(blank=True, help_text='Original trip_ping_fields array data', null=True)),
                ('trip_to_trip_fields', models.JSONField(blank=True, help_text='Original trip_to_trip_fields array data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trip',
                'indexes': [models.Index(fields=['caid'], name='trip_caid_a1543c_idx'), models.Index(fields=['utc_timestamp'], name='trip_utc_tim_02b666_idx'), models.Index(fields=['id_type'], name='trip_id_type_721454_idx'), models.Index(fields=['iso_country_code'], name='trip_iso_cou_526e12_idx'), models.Index(fields=['created_at'], name='trip_created_3f8e47_idx'), models.Index(fields=['start_time', 'end_time'], name='trip_start_t_85e28c_idx')],
            },
        ),
    ]
