# Generated by Django 4.2.26 on 2025-11-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0125_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_visitor',
            field=models.BooleanField(blank=True, db_index=True, default=None, help_text='Whether the trip is from a visitor', null=True),
        ),
        migrations.CreateModel(
            name='TripHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caid', models.CharField(db_index=True, help_text='Cryptographic advertising ID (hashed device identifier)', max_length=64, unique=True)),
                ('is_visitor', models.BooleanField(db_index=True, default=False, help_text='Whether this CAID is a visitor')),
                ('country_iso', models.CharField(blank=True, db_index=True, help_text='ISO 2-letter country code', max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Trip Home',
                'verbose_name_plural': 'Trip Homes',
                'db_table': 'trip_home',
                'indexes': [models.Index(fields=['caid'], name='trip_home_caid_6fe6b3_idx'), models.Index(fields=['is_visitor'], name='trip_home_is_visi_ac00a0_idx'), models.Index(fields=['country_iso'], name='trip_home_country_79d4c6_idx')],
            },
        ),
    ]
