# Generated by Django 4.2.26 on 2025-11-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0126_trip_is_visitor_triphome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOutstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caid', models.CharField(db_index=True, help_text='Cryptographic advertising ID (hashed device identifier)', max_length=64, unique=True)),
                ('record_count', models.IntegerField(help_text='Number of trip records for this CAID')),
                ('start_date', models.DateTimeField(db_index=True, help_text='UTC timestamp of the first trip')),
                ('end_date', models.DateTimeField(db_index=True, help_text='UTC timestamp of the last trip plus its traverse_time')),
                ('total_traverse_time', models.BigIntegerField(help_text='Sum of all traverse_time values (in seconds or milliseconds)')),
                ('total_displacement', models.FloatField(help_text='Sum of all displacement values (distance in meters)')),
                ('total_pings', models.BigIntegerField(help_text='Sum of all pings values')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Trip Outstanding',
                'verbose_name_plural': 'Trips Outstanding',
                'db_table': 'trip_outstanding',
                'ordering': ['-total_displacement'],
                'indexes': [models.Index(fields=['caid'], name='trip_outsta_caid_b9725e_idx'), models.Index(fields=['start_date'], name='trip_outsta_start_d_14a76a_idx'), models.Index(fields=['end_date'], name='trip_outsta_end_dat_105b61_idx'), models.Index(fields=['total_displacement'], name='trip_outsta_total_d_ae21e2_idx'), models.Index(fields=['created_at'], name='trip_outsta_created_f0f2b0_idx')],
            },
        ),
    ]
