# Generated by Django 4.2.26 on 2025-11-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0127_tripoutstanding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='triphome',
            name='trip_home_is_visi_ac00a0_idx',
        ),
        migrations.RemoveField(
            model_name='triphome',
            name='is_visitor',
        ),
        migrations.AddField(
            model_name='triphome',
            name='has_been_processed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this CAID has been processed'),
        ),
        migrations.AddIndex(
            model_name='triphome',
            index=models.Index(fields=['has_been_processed'], name='trip_home_has_bee_e5cd89_idx'),
        ),
    ]
