# Generated by Django 4.2.26 on 2025-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0128_remove_triphome_trip_home_is_visi_ac00a0_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['caid', 'trip_fields'], name='trip_caid_d725bc_idx'),
        ),
    ]
