# Generated by Django 4.2.26 on 2025-11-17 22:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0129_trip_trip_caid_d725bc_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caid', models.CharField(db_index=True, help_text='Cryptographic advertising ID (hashed device identifier)', max_length=64)),
                ('utc_timestamp', models.DateTimeField(db_index=True, help_text='UTC timestamp of the trip event')),
                ('latitude', models.FloatField(help_text='Latitude of the trip location')),
                ('longitude', models.FloatField(help_text='Longitude of the trip location')),
                ('horizontal_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic point for the location', null=True, srid=4326)),
                ('id_type', models.CharField(blank=True, choices=[('idfa', 'IDFA (iOS)'), ('aaid', 'AAID (Android)')], help_text='Ad ID device type: IDFA (iOS) or AAID (Android)', max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the event', null=True)),
                ('iso_country_code', models.CharField(blank=True, db_index=True, help_text='ISO 2-letter country code', max_length=2, null=True)),
                ('poi_ids', models.TextField(blank=True, help_text='Point of Interest IDs (comma-separated or empty)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Basic Trip',
                'verbose_name_plural': 'Basic Trips',
                'db_table': 'basic_trip',
                'ordering': ['-utc_timestamp'],
                'indexes': [models.Index(fields=['caid'], name='basic_trip_caid_a0fd3a_idx'), models.Index(fields=['utc_timestamp'], name='basic_trip_utc_tim_a70db4_idx'), models.Index(fields=['id_type'], name='basic_trip_id_type_e7f340_idx'), models.Index(fields=['iso_country_code'], name='basic_trip_iso_cou_94968e_idx'), models.Index(fields=['created_at'], name='basic_trip_created_fb437e_idx'), models.Index(fields=['caid', 'utc_timestamp'], name='basic_trip_caid_542154_idx')],
            },
        ),
    ]
