# Generated by Django 4.2.26 on 2025-11-18 04:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0130_basictrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvegeo', models.CharField(db_index=True, help_text='Geographic key (CVEGEO)', max_length=20)),
                ('cve_ent', models.CharField(db_index=True, help_text='Entity code (CVE_ENT)', max_length=2)),
                ('cve_mun', models.CharField(db_index=True, help_text='Municipality code (CVE_MUN)', max_length=3)),
                ('cve_loc', models.CharField(blank=True, help_text='Location code (CVE_LOC)', max_length=4, null=True)),
                ('cve_asen', models.CharField(blank=True, help_text='Settlement code (CVE_ASEN)', max_length=4, null=True)),
                ('cp', models.CharField(blank=True, db_index=True, help_text='Postal code (CP)', max_length=10, null=True)),
                ('fecha_act', models.CharField(blank=True, help_text='Update date (FECHA_ACT)', max_length=20, null=True)),
                ('institucion', models.CharField(blank=True, help_text='Institution (INSTITUCIO)', max_length=200, null=True)),
                ('nom_asen', models.CharField(blank=True, db_index=True, help_text='Settlement name (NOM_ASEN)', max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, db_index=True, help_text='Type (TIPO) - e.g., COLONIA', max_length=50, null=True)),
                ('turistico', models.CharField(blank=True, db_index=True, help_text='Touristic classification (TURISTICO)', max_length=20, null=True)),
                ('shape_leng', models.FloatField(blank=True, help_text='Shape length (Shape_Leng)', null=True)),
                ('shape_area', models.FloatField(blank=True, help_text='Shape area (Shape_Area)', null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geographic boundary as MultiPolygon', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Polygon of Interest',
                'verbose_name_plural': 'Polygons of Interest',
                'db_table': 'polygon_of_interest',
                'indexes': [models.Index(fields=['cvegeo'], name='polygon_of__cvegeo_b985cb_idx'), models.Index(fields=['cve_ent'], name='polygon_of__cve_ent_f87241_idx'), models.Index(fields=['cve_mun'], name='polygon_of__cve_mun_26a2d9_idx'), models.Index(fields=['cp'], name='polygon_of__cp_4da680_idx'), models.Index(fields=['nom_asen'], name='polygon_of__nom_ase_c35901_idx'), models.Index(fields=['tipo'], name='polygon_of__tipo_ae0e41_idx'), models.Index(fields=['turistico'], name='polygon_of__turisti_1a87c7_idx'), models.Index(fields=['cve_ent', 'cve_mun'], name='polygon_of__cve_ent_7a2e16_idx')],
            },
        ),
    ]
