# Generated by Django 4.2.26 on 2025-11-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0131_polygonofinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonofinterest',
            name='cve_ent',
            field=models.CharField(blank=True, db_index=True, help_text='Entity code (CVE_ENT)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='polygonofinterest',
            name='cve_mun',
            field=models.CharField(blank=True, db_index=True, help_text='Municipality code (CVE_MUN)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='polygonofinterest',
            name='cvegeo',
            field=models.CharField(blank=True, db_index=True, help_text='Geographic key (CVEGEO)', max_length=20, null=True),
        ),
    ]
