# Generated by Django 4.2.26 on 2025-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0132_alter_polygonofinterest_cve_ent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripsMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_polygon', models.CharField(blank=True, db_index=True, help_text="Origin polygon identifier (Polígono Orígen). Can be 'NA' if not available.", max_length=50, null=True)),
                ('destination_polygon', models.CharField(blank=True, db_index=True, help_text="Destination polygon identifier (Polígono Destino). Can be 'NA' if not available.", max_length=50, null=True)),
                ('date', models.DateField(db_index=True, help_text='Date of the trip (Fecha)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Trip Matching',
                'verbose_name_plural': 'Trips Matching',
                'db_table': 'trips_matching',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['origin_polygon'], name='trips_match_origin__dd4a7e_idx'), models.Index(fields=['destination_polygon'], name='trips_match_destina_915926_idx'), models.Index(fields=['date'], name='trips_match_date_194ad1_idx'), models.Index(fields=['origin_polygon', 'destination_polygon', 'date'], name='trips_match_origin__ffd600_idx')],
            },
        ),
    ]
