# Generated by Django 4.2.26 on 2025-11-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0133_tripsmatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsmatching',
            name='destination_polygon_name',
            field=models.CharField(blank=True, help_text='Name of the destination polygon (e.g., settlement name)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripsmatching',
            name='origin_polygon_name',
            field=models.CharField(blank=True, help_text='Name of the origin polygon (e.g., settlement name)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripsmatching',
            name='trip_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier for the trip', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='tripsmatching',
            index=models.Index(fields=['trip_id'], name='trips_match_trip_id_a87bf1_idx'),
        ),
    ]
