# Generated by Django 4.2.26 on 2025-11-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0134_tripsmatching_destination_polygon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsmatching',
            name='time_of_day',
            field=models.CharField(blank=True, db_index=True, help_text="Time of day category (e.g., 'morning', 'afternoon', 'evening', 'night')", max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='tripsmatching',
            index=models.Index(fields=['time_of_day'], name='trips_match_time_of_c2747b_idx'),
        ),
    ]
