# Generated by Django 4.2.26 on 2025-11-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0135_tripsmatching_time_of_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='tourist_visitors_average_daily_evening_november',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tourist_visitors_average_daily_morning_november',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tourist_visitors_average_daily_november',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tourist_visitors_november',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
