# Generated by Django 4.2.26 on 2025-11-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0136_neighbourhood_tourist_visitors_average_daily_evening_november_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='tourist_visitors_average_daily_afternoon_november',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
