# Generated by Django 4.2.26 on 2025-11-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0137_neighbourhood_tourist_visitors_average_daily_afternoon_november'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='tourist_visitors_november_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        # Remove the old integer field first
        migrations.RemoveField(
            model_name='neighbourhood',
            name='tourist_visitors_november',
        ),
        # Add the new JSONField
        migrations.AddField(
            model_name='neighbourhood',
            name='tourist_visitors_november',
            field=models.JSONField(blank=True, help_text='Daily statistics for November. Dictionary with day keys (01-30) containing d (daily), m (morning), a (afternoon), e (evening) counts', null=True),
        ),
    ]
