# Generated by Django 4.2.26 on 2025-11-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0138_neighbourhood_tourist_visitors_november_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='tourist_visitors_average_daily_afternoon_november',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='tourist_visitors_average_daily_evening_november',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='tourist_visitors_average_daily_morning_november',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='tourist_visitors_average_daily_november',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='tourist_visitors_november',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='tourist_visitors_november_total',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='tourist_visitors_info',
            field=models.JSONField(blank=True, help_text='Tourist visitor statistics organized by year-month. Each month contains total, averages, and daily breakdown.', null=True),
        ),
    ]
