# Generated by Django 4.2.30 on 2026-07-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0139_remove_neighbourhood_tourist_visitors_average_daily_afternoon_november_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespojoCaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('borough', models.CharField(blank=True, max_length=80)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('year_of_events', models.IntegerField(blank=True, null=True)),
                ('denuncia_status', models.CharField(blank=True, choices=[('with_folio', 'Denunció y tiene número de carpeta'), ('without_folio', 'Denunció pero no tiene el número'), ('not_reported', 'No ha denunciado'), ('refused', 'Lo intentó y no se la recibieron')], max_length=20)),
                ('account', models.TextField(blank=True, max_length=4000)),
                ('consent_contact', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('new', 'Sin revisar'), ('contacted', 'Contactado'), ('closed', 'Cerrado')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte de despojo',
                'verbose_name_plural': 'Reportes de despojo',
                'db_table': 'despojo_case_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='despojo_cas_created_7b0d13_idx'), models.Index(fields=['review_status'], name='despojo_cas_review__376f29_idx')],
            },
        ),
    ]
