# Generated by Django 4.2.30 on 2026-07-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0140_despojocasereport'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='felony',
            index=models.Index(fields=['crime_type', 'crime_year', 'crime_date'], name='felony_type_year_date_idx'),
        ),
    ]
