# Generated by Django 4.2.30 on 2026-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0143_despojonewsfeed_despojonewskeyword_despojonewsrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=4000)),
                ('source_path', models.CharField(blank=True, max_length=200)),
                ('review_status', models.CharField(choices=[('new', 'Sin revisar'), ('contacted', 'Contactado'), ('closed', 'Cerrado')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead de contacto',
                'verbose_name_plural': 'Leads de contacto',
                'db_table': 'contact_leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contact_lea_created_539743_idx'), models.Index(fields=['review_status'], name='contact_lea_review__a39f03_idx')],
            },
        ),
    ]
