# Generated by Django 4.2.30 on 2026-07-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0144_contactlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despojonewsrun',
            name='trigger',
            field=models.CharField(choices=[('dashboard', 'Manual desde el panel'), ('admin', 'Manual desde el admin'), ('command', 'Línea de comandos')], default='admin', max_length=20),
        ),
    ]
