# Generated by Django 4.2.30 on 2026-07-30 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0145_alter_despojonewsrun_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespojoNewsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rail_limit', models.PositiveSmallIntegerField(default=4, help_text='Cuántas notas publicadas muestra el riel del mapa, de la más reciente hacia atrás.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Notas visibles en el mapa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Ajustes del riel de noticias (despojo)',
                'verbose_name_plural': 'Ajustes del riel de noticias (despojo)',
                'db_table': 'despojo_news_settings',
            },
        ),
    ]
